---
ID: "602018ad-fc07-4db5-b502-46d0da748e29"
Parent: "2cc79456-86bc-4ea7-b5a4-e38f73d3f184"
Template: "83746e54-66fe-4fd4-b79d-ff3fd4acd903"
Path: /sitecore/content/Sitecore/Demo B/Presentation/Enumerations/Page Content/Button Icons/default
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{9F30B1DF-9AA3-4471-9A9E-89858E2399F6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250131T180727Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b6cb2980-b9af-4288-ab02-bf425dbd0c8e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250131T180727Z
