---
ID: "a09125a0-706a-4c72-a0a6-354f3c7600ef"
Parent: "22c53a61-7af2-4cc6-86a5-06e0fdb85ee5"
Template: "22c53a61-7af2-4cc6-86a5-06e0fdb85ee5"
Path: /sitecore/templates/Feature/Velir Headless Experience Accelerator/Page Content/Vertical Image Accordion/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E64D342F-E5AA-4233-88C4-58CCD451A7D3}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250403T132218Z
    - ID: "32737efc-143d-4ed5-b1e0-99c362c6ba9a"
      Hint: titleOptional
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "986a9148-406e-49c1-bd36-56f8b2cbcceb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250403T133036Z
