---
ID: "c0b47951-98ae-46f9-89e6-81eca2a420b8"
Parent: "7bcc6b50-ea9e-457d-b232-c5cee2090b9f"
Template: "7bcc6b50-ea9e-457d-b232-c5cee2090b9f"
Path: /sitecore/templates/Feature/Velir Headless Experience Accelerator/Page Content/Topic/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250303T214900Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "448121fe-bed1-47ab-b382-3b8f07705efc"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250303T214900Z
