---
ID: "376da354-62fb-4066-ade3-439419eae7a8"
Parent: "877091a7-131e-40d2-bdc6-5534284c5d03"
Template: "9f6e14e6-c593-410b-a57e-21f6b5a413ad"
Path: /sitecore/system/Settings/Buckets/Item Buckets Settings
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/32x32/gear.png
- ID: "37ac831a-7cb4-4962-aebd-a269649e5d35"
  Hint: Tag Parent
  Value: "{154D56CC-0DE2-43C7-BBC0-A25BD7FFD901}"
- ID: "5a81d794-7364-4cc5-8aa9-a921d5dda4af"
  Hint: Opening Search Results
  Value: New Tab
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111026T183900Z
    - ID: "4b5d1cb7-e617-4cd0-a7e8-cc8a9fd80688"
      Hint: Rule
      Value: |
        <ruleset>
          <rule
            uid="{076BF96F-ABE9-4CD4-BE8F-D851AB6304A9}">
            <conditions>
              <and
                uid="81AB9BD66FF645359ED472129B7C9AED">
                <condition
                  id="{4A505FF0-50A8-4B84-84CF-0CAD8EF3D695}"
                  uid="4B1871FB0EBA4B2586241D6AD2A08638"
                  templateid="{C47DFAEB-390A-4092-8716-39899E70E125}" />
                <condition
                  id="{E5B43654-4D96-41F3-83D6-4F04CC7ADF69}"
                  uid="823F2CCF0B7B474D9B2391D0B68A4F24"
                  templateid="{B75B7839-359D-45C6-9432-A1F11C35B4F4}" />
              </and>
            </conditions>
            <actions>
              <action
                id="{F091DB35-8784-44D7-A7FA-0729984188DF}"
                uid="9A1730E5C72747E6AB17B393C4A96396"
                levels="1" />
            </actions>
          </rule>
        </ruleset>
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bfe2b7d3-8810-458f-a054-6668c3cbe9d3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250303T230043Z
