---
ID: "295de4e1-da68-456e-b474-9128532c6dcd"
Parent: "e64d342f-e5aa-4233-88c4-58ccd451a7d3"
Template: "e64d342f-e5aa-4233-88c4-58ccd451a7d3"
Path: /sitecore/templates/Feature/Velir Headless Experience Accelerator/Page Content/Vertical Accordion Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250403T132544Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "6ef0efde-7773-4786-af78-860ff2f4eeac"
      Hint: titleRequired
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1212e01e-f81d-442f-b38c-397d12d6dd98"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250403T132550Z
