---
ID: "defabff0-316a-452b-80b0-3d8800587255"
Parent: "732743bf-a340-4525-96c2-e556e9fa2bd8"
Template: "732743bf-a340-4525-96c2-e556e9fa2bd8"
Path: /sitecore/templates/Feature/Velir Headless Experience Accelerator/Page Structure/Rendering Parameters/Container 70/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8d96d99d-0932-4625-962d-68bd6b32de06"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250224T192227Z
