---
ID: "82a9b9e5-d2c8-496c-af23-92c197b36bcb"
Parent: "619cc013-e6ed-4e26-92ae-d6ad48a3b19b"
Template: "83746e54-66fe-4fd4-b79d-ff3fd4acd903"
Path: /sitecore/content/Sitecore/Demo B/Presentation/Enumerations/Page Headers/Color Schemes/default
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0C038C3A-481B-480C-AD8B-4FDEF74CCA08}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250131T180715Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8894c670-692b-48fa-ba95-524083ae6821"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250131T180715Z
