---
ID: "cd41ef9b-aeab-4c5b-bd28-ecdc8fe51036"
Parent: "dacf78ba-647c-4185-a6e5-f56111cb61bf"
Template: "83746e54-66fe-4fd4-b79d-ff3fd4acd903"
Path: /sitecore/content/Sitecore/Demo A/Presentation/Enumerations/Page Headers/Color Schemes/default
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0C038C3A-481B-480C-AD8B-4FDEF74CCA08}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250131T181140Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "291c6c30-c277-45f2-b75d-0ec4ea376f88"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250131T181140Z
