---
ID: "8d138c13-8aae-435f-91c2-0906ccf3f9e7"
Parent: "dbfc02bc-5071-4cd1-b573-789bc92c722f"
Template: "dbfc02bc-5071-4cd1-b573-789bc92c722f"
Path: /sitecore/templates/Feature/Velir Headless Experience Accelerator/Page Content/_Article Base/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250303T230538Z
    - ID: "2fcae033-cf44-4b77-b8ad-91f41b56cb1c"
      Hint: pageDisplayDate
      Value: $date
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3e73072d-172a-428e-b669-7d058c6d61c9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250303T230725Z
