---
ID: "dbf47849-4c30-4338-9b5f-64cd4e97a535"
Parent: "73b9712c-9f1a-47f9-8a20-1cc9d2a10795"
Template: "83746e54-66fe-4fd4-b79d-ff3fd4acd903"
Path: /sitecore/content/Sitecore/Demo B/Presentation/Enumerations/Banners/Layout/default
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{40205468-4740-48E2-96D6-2D39C30FD3C5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250131T180719Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6a33f8b9-d23f-41a7-bfa9-fd1fd41da8f3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\dylan.young@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250131T180719Z
