---
ID: "2ca93be7-0047-41f1-ae32-340e0baa7d3f"
Parent: "18214baa-104a-4f82-bfb2-4f8a33957447"
Template: "18214baa-104a-4f82-bfb2-4f8a33957447"
Path: /sitecore/templates/Feature/Velir Headless Experience Accelerator/Promos/Rendering Parameters/Subscription Banner Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "62ae88be-a68d-4ea2-b929-ef879e63b499"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\minyie.diaz@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250326T151001Z
